export const registration = [
  {
    name: 'email',
    type: 'email',
    labelText: 'Email',
    required: true,
    minLength: 6,
    maxLength: 20,
  },
  {
    name: 'password',
    type: 'password',
    labelText: 'Password',
    required: true,
    minLength: 8,
    maxLength: 64,
  },
];

export const AddStudentForm = [
  {
    name: 'name',
    type: 'text',
    labelText: 'Name',
    required: true,
    minLength: 2,
    maxLength: 50,
    iconClass: 'fas fa-user',
  },
  {
    name: 'surname',
    type: 'text',
    labelText: 'Surname',
    required: true,
    minLength: 2,
    maxLength: 50,
    iconClass: 'fas fa-user',
  },
  {
    name: 'email',
    type: 'email',
    labelText: 'Email',
    required: true,
    minLength: 2,
    maxLength: 50,
  },
  {
    name: 'phone',
    type: 'text',
    labelText: 'Phone',
    required: true,
    minLength: 5,
    maxLength: 15,
    iconClass: 'fas fa-phone',
  },
];
export const AddCourseForm = [
  {
    name: 'title',
    type: 'text',
    labelText: 'Course Title',
    required: true,
    minLength: 2,
    maxLength: 50,
    iconClass: 'fas fa-book-reader',
  },
  {
    name: 'lecturer',
    type: 'text',
    labelText: 'Lecturer',
    required: true,
    minLength: 2,
    maxLength: 50,
    iconClass: 'fas fa-chalkboard-teacher',
  },
  {
    name: 'description',
    type: 'text',
    labelText: 'Description',
    required: true,
    minLength: 2,
    maxLength: 50,
    iconClass: 'fas fa-info',
  },
];
